<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <EnableDefaultCompileItems>false</EnableDefaultCompileItems>
    <DefineConstants>$(DefineConstants);SWIR_PACKAGE_SIGNATURE_TOOL</DefineConstants>
    <StartupObject>Swir.Desktop.Host.DesktopPackageSignatureTool</StartupObject>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="DesktopAppPackageInstaller.cs" />
    <Compile Include="DesktopPackageSignatureVerifier.cs" />
    <Compile Include="DesktopPackageSignatureTool.cs" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="NSec.Cryptography" Version="24.4.0" />
  </ItemGroup>
</Project>
